#!/usr/bin/env bash

cd /app/wildfly

[ -f /etc/container_environment/JAVA_XMS ] && JAVA_XMS=$(cat /etc/container_environment/JAVA_XMS) || JAVA_XMS=20m
[ -f /etc/container_environment/JAVA_XMX ] && JAVA_XMX=$(cat /etc/container_environment/JAVA_XMX) || JAVA_XMX=512m
[ -f /etc/container_environment/JVM_OPTS ] && JVM_OPTS=$(cat /etc/container_environment/JVM_OPTS) || JVM_OPTS=""
[ -f /etc/container_environment/JAVA_OPTS ] && JAVA_OPTS=$(cat /etc/container_environment/JAVA_OPTS) || JAVA_OPTS=""
JAVA_OPTS=" -Xms${JAVA_XMS} -Xmx${JAVA_XMX} ${JVM_OPTS} ${JAVA_OPTS} "
[ -e /etc/container_environment/SERVER_OPTS ] && SERVER_OPTS=$(cat /etc/container_environment/SERVER_OPTS)
SERVER_PARAMS=$(cat /etc/container_environment/SERVER_PARAMS)
HOSTIP=$(cat /etc/container_environment/HOSTIP)
WILDFLY_CONFIG_DIR=$(cat /etc/container_environment/WILDFLY_CONFIG_DIR)
WILDFLY_DATA_DIR=$(cat /etc/container_environment/WILDFLY_DATA_DIR)
WILDFLY_LOG_DIR=$(cat /etc/container_environment/WILDFLY_LOG_DIR)
WILDFLY_TMP_DIR=$(cat /etc/container_environment/WILDFLY_TMP_DIR)

exec setuser system ./bin/standalone.sh \
    -b=${HOSTIP} \
    -bmanagement=${HOSTIP} \
    -Djboss.server.config.dir=${WILDFLY_CONFIG_DIR} \
    -Djboss.server.data.dir=${WILDFLY_DATA_DIR} \
    -Djboss.server.log.dir=${WILDFLY_LOG_DIR} \
    -Djboss.server.temp.dir=${WILDFLY_TMP_DIR} \
    ${SERVER_PARAMS}
